{
  return (IOException)new IOException().initCause(x);
}
