{
  try {
    content.succeeded();
    process();
  }
 catch (  Exception x) {
    anyToFailure(x);
  }
}
