{
  try {
    send(part3);
    Assert.fail("Expected a IOException on this send");
  }
 catch (  IOException ignore) {
  }
}
