{
  try {
    if (callback != null)     callback.failed(x);
  }
 catch (  Exception xx) {
    logger.info("Exception while notifying callback " + callback,xx);
  }
catch (  Error xx) {
    logger.info("Exception while notifying callback " + callback,xx);
    throw xx;
  }
}
