{
  try {
    listener.onFailure(response,failure);
  }
 catch (  Exception x) {
    LOG.info("Exception while notifying listener " + listener,x);
  }
}
