{
  try {
    flush(false);
  }
 catch (  Throwable x) {
    notifyFailure(x);
    throw x;
  }
}
