{
  try {
    _server.stop();
  }
 catch (  Exception e) {
    _context.log("stopping",e);
  }
}
