{
  try {
    endpoint.onError(jsrsession,cause);
  }
 catch (  Throwable t) {
    LOG.warn("Unable to report to onError due to exception",t);
  }
}
