{
  Throwable cause=e.getCause();
  Assert.assertThat("ExecutionException.cause",cause,instanceOf(errorClass));
  Assert.assertThat("Error Queue Length",wsocket.errorQueue.size(),greaterThanOrEqualTo(1));
  Throwable capcause=wsocket.errorQueue.poll();
  Assert.assertThat("Error Queue[0]",capcause,notNullValue());
  Assert.assertThat("Error Queue[0]",capcause,instanceOf(errorClass));
  wsocket.assertNotOpened();
  return (E)capcause;
}
