{
  if (_ready)   return true;
  throw new ExecutionException(_cause);
}
