{
  try {
    transformer.transform(input,finished,output);
  }
 catch (  Throwable x) {
    _log.info("Exception while transforming " + transformer,x);
    throw x;
  }
}
