{
  try {
    super.callback(instance);
  }
 catch (  Exception e) {
    Log.warn("Ignoring exception thrown on preDestroy call to " + getTargetClass() + "."+ getTarget().getName(),e);
  }
}
