{
  close(ErrorCode.INTERNAL_ERROR,"generator_error",Adapter.INSTANCE);
  callback.failed(x);
}
